require 'prawn'

class PDFReportGenerator
  def initialize(record)
    @record = record
  end

  def generate
    Prawn::Fonts::AFM.hide_m17n_warning = true

    pdf = Prawn::Document.new(page_size: 'A4', margin: 40)
    
    primary_color = "4F46E5" # Indigo
    text_color = "1E293B"    # Charcoal
    bg_color = "F8FAFC"      # Slate Light
    border_color = "E2E8F0"  # Light Grey
    
    pdf.font "Helvetica"
    
    # Top header bar
    pdf.fill_color primary_color
    pdf.fill_rectangle [0, 780], 515, 60
    
    pdf.fill_color "FFFFFF"
    pdf.text_box "CAREERMIND AI — CV INTELLIGENCE REPORT", 
                 at: [15, 762], 
                 size: 13, 
                 style: :bold
    
    pdf.text_box "AI-Powered Resume Analytics and Career Insights Engine", 
                 at: [15, 742], 
                 size: 8, 
                 style: :italic
                 
    # Meta Details Block
    pdf.fill_color text_color
    pdf.move_down 80
    
    pdf.text "Candidate Name: #{clean_latin(@record.personal_info['name'] || 'Candidate')}", size: 12, style: :bold
    pdf.text "Filename: #{clean_latin(@record.filename)}", size: 10
    pdf.text "Target Focus: #{clean_latin(@record.career_recommendations.first&.[]('role') || 'Software Engineering')}", size: 11
    pdf.text "Email: #{clean_latin(@record.personal_info['email'] || 'Not specified')}", size: 10
    pdf.text "LinkedIn: #{clean_latin(@record.personal_info['linkedin'] ? 'linkedin.com/in/' + @record.personal_info['linkedin'] : 'Not specified')}", size: 10
    pdf.text "GitHub: #{clean_latin(@record.personal_info['github'] ? 'github.com/' + @record.personal_info['github'] : 'Not specified')}", size: 10
    pdf.text "Report Date: #{Time.parse(@record.created_at).strftime('%Y-%m-%d %H:%M')}", size: 9, style: :italic
    
    pdf.stroke_color border_color
    pdf.stroke_horizontal_line 0, 515, at: pdf.y - 12
    pdf.move_down 25
    
    # Score metrics grid
    pdf.text "SCORE METRICS", size: 11, style: :bold, color: primary_color
    pdf.move_down 8
    
    # Draw scores container box
    pdf.fill_color bg_color
    pdf.fill_rounded_rectangle [0, pdf.y], 515, 70, 4
    pdf.fill_color text_color
    
    y_pos = pdf.y - 12
    pdf.text_box "Overall score", at: [15, y_pos], size: 8, style: :bold
    pdf.text_box "#{@record.scores['general']}/100", at: [15, y_pos - 12], size: 22, style: :bold
    
    pdf.text_box "ATS Match", at: [125, y_pos], size: 8, style: :bold
    pdf.text_box "#{@record.scores['ats']}/100", at: [125, y_pos - 12], size: 16, style: :bold
    
    pdf.text_box "Tech Competence", at: [225, y_pos], size: 8, style: :bold
    pdf.text_box "#{@record.scores['tech']}/100", at: [225, y_pos - 12], size: 16, style: :bold
    
    pdf.text_box "Presentation Style", at: [335, y_pos], size: 8, style: :bold
    pdf.text_box "#{@record.scores['presentation']}/100", at: [335, y_pos - 12], size: 16, style: :bold
    
    pdf.text_box "Employability", at: [435, y_pos], size: 8, style: :bold
    pdf.text_box "#{@record.scores['employability']}/100", at: [435, y_pos - 12], size: 16, style: :bold
    
    pdf.move_down 85
    
    # Strengths, Weaknesses, Suggestions
    pdf.text "KEY HIGHLIGHTS", size: 11, style: :bold, color: primary_color
    pdf.stroke_horizontal_line 0, 515, at: pdf.y - 4
    pdf.move_down 15
    
    pdf.text "Strengths:", size: 10, style: :bold
    @record.highlights['strengths'].each do |str|
      pdf.text "  • #{clean_latin(str)}", size: 9
    end
    pdf.move_down 8
    
    pdf.text "Areas for Improvement / Gaps:", size: 10, style: :bold
    @record.highlights['weaknesses'].each do |wk|
      pdf.text "  • #{clean_latin(wk)}", size: 9
    end
    pdf.move_down 8
    
    pdf.text "Actionable Suggestions:", size: 10, style: :bold
    @record.highlights['suggestions'].each do |sug|
      pdf.text "  • #{clean_latin(sug)}", size: 9
    end
    
    pdf.move_down 20
    
    # Career recommendations
    pdf.text "CAREER PATH RECOMMENDATIONS & SKILLS GAP ANALYSIS", size: 11, style: :bold, color: primary_color
    pdf.stroke_horizontal_line 0, 515, at: pdf.y - 4
    pdf.move_down 15
    
    @record.career_recommendations.first(3).each do |rec|
      pdf.text "Role: #{clean_latin(rec['role'])} (Estimated Match: #{rec['match_percentage']}%)", size: 10, style: :bold
      pdf.text "#{clean_latin(rec['description'])}", size: 9, style: :italic
      
      gaps = @record.missing_skills[rec['role']] || []
      if !gaps.empty?
        pdf.text "Target Skill Gaps: #{clean_latin(gaps.join(', '))}", size: 9, style: :bold
      end
      pdf.move_down 12
    end
    
    pdf.move_down 15
    pdf.stroke_horizontal_line 0, 515, at: pdf.y
    pdf.move_down 10
    
    pdf.text "Report generated by CareerMind AI Platform. Use these findings to refine and optimize your profile before applying.", 
             size: 8, 
             style: :italic, 
             align: :center, 
             color: "666666"

    pdf.render
  end

  private

  def clean_latin(text)
    return "" if text.nil?
    text = text.to_s
    tr_map = {
      'ş' => 's', 'Ş' => 'S',
      'ğ' => 'g', 'Ğ' => 'G',
      'ç' => 'c', 'Ç' => 'C',
      'ı' => 'i', 'İ' => 'I',
      'ö' => 'o', 'Ö' => 'O',
      'ü' => 'u', 'Ü' => 'U'
    }
    tr_map.each { |k, v| text = text.gsub(k, v) }
    text.encode('ASCII', invalid: :replace, undef: :replace, replace: '')
  end
end
