module ApplicationHelper
  DICTIONARY = {
    'en' => {
      title: "AI-Powered Resume Intelligence Platform",
      subtitle: "Transform Your Resume Into A Career Opportunity",
      drag_drop: "Drag & Drop your resume here",
      formats: "Supports PDF, DOCX, or plain text formats (Max 5MB)",
      browse: "Browse File",
      history: "Analysis History",
      no_reports: "No reports generated yet. Upload your resume to start.",
      total_processed: "Total Resumes Processed",
      avg_score: "Average Resume Score",
      in_demand: "In-Demand Skills Detected",
      top_skills_sub: "Top technical skills found across all database CV files",
      score_breakdown: "Score Quality Breakdown",
      score_breakdown_sub: "Analysis distribution by standard scoring bands",
      excellent: "Excellent",
      good: "Good",
      average: "Average",
      critical: "Critical",
      quality_sub: "Quality Sub-metrics",
      quality_sub_desc: "Category evaluation results out of 100",
      ats_comp: "ATS Compatibility",
      tech_comp: "Technical Competence",
      prof_pres: "Professional Presentation",
      employability: "Employability Rating",
      tech_map: "Technology Map",
      tech_map_sub: "Technical skills density by category",
      strong_points: "Strong Points",
      structural_gaps: "Structural Gaps",
      suggestions: "Actionable Suggestions",
      career_rec: "AI Career Recommendation & Gap Analysis",
      career_rec_sub: "Matching technical profile capabilities with industry standard requirements",
      matched_skills: "Matched Skills",
      target_gaps: "Recommended Target Skill Gaps",
      taxonomy: "Detected Skills Taxonomy",
      taxonomy_sub: "Categorized list of technical skills parsed from resume content",
      download_pdf: "Download PDF Report",
      back: "Back",
      analyze_new: "Analyze New Resume",
      empty_history: "No reports generated yet.",
      parsing: "CV Parsing...",
      skills: "Skill Detection...",
      ats_analysis: "ATS Analysis...",
      matching: "Career Matching...",
      report: "Generating Report...",
      analyzing_profile: "Analyzing Profile",
      evaluating_experience: "Evaluating candidate experience and skill taxonomy...",
      overall_score: "Overall score",
      report_generated: "Report generated by CareerMind AI Platform. Use these findings to refine and optimize your profile before applying.",
      gaps_complete: "Complete profile matches!",
      guide_title: "AI Professional CV Builder Guide",
      guide_subtitle: "Contextual templates, comparative examples, and structural guidelines tailored to your profile gaps.",
      before_lbl: "Current / Unoptimized (Before)",
      after_lbl: "Recommended Revision (After)",
      copy_lbl: "Copy to Clipboard",
      placement_lbl: "Recommended Placement Location",
      roadmap_title: "Tech Integration Roadmap (3-Month Action Plan)",
      roadmap_subtitle: "Step-by-step roadmap to acquire missing technologies and showcase them in your projects.",
      roadmap_stage: "Stage",
      roadmap_objective: "Target Objective",
      roadmap_tasks: "Key Tasks",
      interview_title: "AI Interview Simulator & Prep Guide",
      interview_subtitle: "Custom-tailored behavioral and technical interview questions based on your profile gaps.",
      question_lbl: "Question",
      context_lbl: "Why they ask this",
      answer_lbl: "Suggested Response Guideline",
      tab_analysis: "Resume Metrics",
      tab_roadmap: "Tech Roadmap",
      tab_interview: "Interview Prep",
      tab_chat: "AI Career Chat",
      tab_matcher: "Job Target Align",
      settings_title: "AI & Model Settings",
      settings_provider: "AI Service Provider",
      settings_api_key: "Enter API Key",
      settings_save: "Save API Settings",
      settings_success: "API Settings saved!",
      settings_desc: "Configure API keys to unlock advanced real-time AI capabilities. Keys are saved securely in your session.",
      chat_welcome: "Welcome to CareerMind AI Assistant! Discuss your resume, request target project plans, or get interview advice.",
      chat_placeholder: "Type your message here...",
      chat_send: "Send",
      chat_suggest_1: "How can I improve my missing skills?",
      chat_suggest_2: "Suggest 3 custom project ideas for me",
      chat_suggest_3: "Rewrite my profile summary for a Tech Lead role",
      matcher_title: "Target Job Description Matcher",
      matcher_desc: "Paste a target job posting below to evaluate how your CV aligns with their specific requirements.",
      matcher_placeholder: "Paste the job description text here...",
      matcher_btn: "Analyze Job Match",
      matcher_matching_score: "Job Match Alignment",
      matcher_matched_keywords: "Matching Keywords Found",
      matcher_missing_keywords: "Critical Keywords Missing",
      matcher_tailoring_suggestions: "Tuning Suggestions for this Job",
      interview_practice: "Practice This Question",
      interview_user_answer: "Type your answer below:",
      interview_submit: "Submit Answer for Grading",
      interview_grading: "Live Grading Report",
      interview_score: "Grading Score",
      interview_strengths: "What You Explained Well",
      interview_gaps: "Gaps to Improve In Your Answer",
      interview_refined: "Refined Model Response",
      interview_close: "Close Simulation"
    },
    'tr' => {
      title: "Yapay Zeka Destekli CV Analiz Platformu",
      subtitle: "CV'nizi Bir Kariyer Fırsatına Dönüştürün",
      drag_drop: "CV'nizi buraya sürükleyip bırakın",
      formats: "PDF, DOCX veya düz metin formatlarını destekler (Maks. 5MB)",
      browse: "Dosya Seçin",
      history: "Analiz Geçmişi",
      no_reports: "Henüz rapor oluşturulmadı. Başlamak için CV'nizi yükleyin.",
      total_processed: "Toplam İncelenen CV",
      avg_score: "Ortalama CV Skoru",
      in_demand: "Tespit Edilen Popüler Yetkinlikler",
      top_skills_sub: "Veritabanındaki CV'lerde en çok rastlanan teknik beceriler",
      score_breakdown: "Skor Dağılım Analizi",
      score_breakdown_sub: "Standart puan aralıklarına göre analiz dağılımı",
      excellent: "Mükemmel",
      good: "İyi",
      average: "Ortalama",
      critical: "Kritik",
      quality_sub: "Kalite Kriterleri Detayı",
      quality_sub_desc: "100 üzerinden kategori bazlı Değerlendirme sonuçları",
      ats_comp: "ATS Uyumluluğu",
      tech_comp: "Teknik Yeterlilik",
      prof_pres: "Profesyonel Sunum",
      employability: "İşe Alınabilirlik Oranı",
      tech_map: "Teknoloji Haritası",
      tech_map_sub: "Kategoriye göre teknik beceri yoğunluğu",
      strong_points: "Güçlü Yönler",
      structural_gaps: "Eksikler ve Gelişim Alanları",
      suggestions: "Profesyonel Öneriler",
      career_rec: "Yapay Zeka Kariyer Önerileri ve Eksik Yetkinlik Analizi",
      career_rec_sub: "Teknik profil yetkinliklerinin sektör standartları ile karşılaştırılması",
      matched_skills: "Uyuşan Yetkinlikler",
      target_gaps: "Hedef Pozisyon İçin Gerekli Eksik Beceriler",
      taxonomy: "Tespit Edilen Yetkinlik Taksonomisi",
      taxonomy_sub: "CV içeriğinden filtrelenen teknik becerilerin kategorize edilmiş listesi",
      download_pdf: "PDF Raporu İndir",
      back: "Geri Dön",
      analyze_new: "Yeni CV Analiz Et",
      empty_history: "Henüz analiz kaydı bulunmuyor.",
      parsing: "CV Ayrıştırılıyor...",
      skills: "Yetkinlikler Tespit Ediliyor...",
      ats_analysis: "ATS Analizi Yapılıyor...",
      matching: "Kariyer Eşleştirmesi Yapılıyor...",
      report: "Rapor Oluşturuluyor...",
      analyzing_profile: "Profil Analiz Ediliyor",
      evaluating_experience: "Deneyim geçmişi ve yetkinlik haritası değerlendiriliyor...",
      overall_score: "Genel Skor",
      report_generated: "Rapor CareerMind AI Platformu tarafından üretilmiştir. Başvurularınızdan önce profilinizi optimize etmek için bu bulguları kullanın.",
      gaps_complete: "Profil yetkinlikleri tam olarak uyuşuyor!",
      guide_title: "Yapay Zeka Destekli CV Geliştirme Kılavuzu",
      guide_subtitle: "Profilinizdeki eksikliklere göre özel olarak hazırlanan şablonlar, konumlandırma rehberi ve karşılaştırmalı örnekler.",
      before_lbl: "Mevcut / Zayıf Örnek (Önce)",
      after_lbl: "Önerilen Revizyon ve Şablon (Sonra)",
      copy_lbl: "Panoya Kopyala",
      placement_lbl: "Ekleneceği Önerilen Konum",
      roadmap_title: "Teknoloji Entegrasyon Yol Haritası (3 Aylık Eylem Planı)",
      roadmap_subtitle: "Eksik teknolojileri öğrenmek ve projelerinize entegre etmek için adım adım gelişim planı.",
      roadmap_stage: "Aşama",
      roadmap_objective: "Hedeflenen Amaç",
      roadmap_tasks: "Yapılması Gerekenler",
      interview_title: "Yapay Zeka Mülakat Simülatörü ve Hazırlık Kılavuzu",
      interview_subtitle: "Profilinizdeki eksikliklere göre size özel olarak kurgulanan teknik ve davranışsal mülakat soruları.",
      question_lbl: "Soru",
      context_lbl: "Sorulma Amacı",
      answer_lbl: "Önerilen Cevap Taslağı",
      tab_analysis: "CV Analiz Raporu",
      tab_roadmap: "Gelişim Yol Haritası",
      tab_interview: "Mülakat Hazırlığı",
      tab_chat: "AI Kariyer Asistanı",
      tab_matcher: "Hedef Pozisyon Eşleme",
      settings_title: "AI ve Model Ayarları",
      settings_provider: "Yapay Zeka Servisi",
      settings_api_key: "API Anahtarını Girin",
      settings_save: "Ayarları Kaydet",
      settings_success: "API Ayarları Kaydedildi!",
      settings_desc: "Gelişmiş gerçek zamanlı AI özelliklerini açmak için API anahtarlarını girin. Anahtarlar oturumunuzda güvenle saklanır.",
      chat_welcome: "CareerMind AI Asistanına Hoş Geldiniz! CV'niz hakkında konuşabilir, proje önerileri isteyebilir veya mülakat tüyoları alabilirsiniz.",
      chat_placeholder: "Mesajınızı buraya yazın...",
      chat_send: "Gönder",
      chat_suggest_1: "Eksik yetkinliklerimi nasıl kapatabilirim?",
      chat_suggest_2: "Benim için 3 özel proje fikri önerir misin?",
      chat_suggest_3: "CV özetimi Tech Lead pozisyonuna göre yeniden yaz",
      matcher_title: "Hedef İş Tanımı Eşleştirici",
      matcher_desc: "Özgeçmişinizin ilandaki kriterlere ne kadar uyduğunu ölçmek için hedef iş ilanının metnini aşağıya yapıştırın.",
      matcher_placeholder: "İş ilanı metnini buraya yapıştırın...",
      matcher_btn: "Uyum Analizini Başlat",
      matcher_matching_score: "İş Uyum Skoru",
      matcher_matched_keywords: "Eşleşen Anahtar Kelimeler",
      matcher_missing_keywords: "Eksik Kritik Anahtar Kelimeler",
      matcher_tailoring_suggestions: "Bu İlan İçin CV Düzenleme Önerileri",
      interview_practice: "Bu Soruyu Yanıtla (Pratik)",
      interview_user_answer: "Cevabınızı buraya yazın:",
      interview_submit: "Cevabı Değerlendir",
      interview_grading: "Mülakat Değerlendirme Raporu",
      interview_score: "Değerlendirme Puanı",
      interview_strengths: "Cevabınızdaki Güçlü Yanlar",
      interview_gaps: "Geliştirilmesi Gereken Noktalar",
      interview_refined: "Profesyonel Örnek Cevap",
      interview_close: "Simülasyonu Kapat"
    }
  }

  FEEDBACK_MAP = {
    # Strengths
    "Technical skills section is highly defined with rich industry technology keywords." => {
      'tr' => "Teknik beceriler bölümü endüstriyel anahtar kelimeler açısından oldukça zengin."
    },
    "Educational background is clearly documented with standard structures." => {
      'tr' => "Eğitim geçmişi standart formatta açıkça belgelenmiş."
    },
    "Project portfolio and hands-on experience are outlined effectively." => {
      'tr' => "Proje portföyü ve pratik deneyimler etkili bir şekilde sunulmuş."
    },
    "Work history emphasizes strong quantitative accomplishments." => {
      'tr' => "İş geçmişi ölçülebilir başarıları ve metrikleri vurguluyor."
    },
    "Demonstrates clear leadership, team mentoring, or project coordination capabilities." => {
      'tr' => "Liderlik, takım mentörlüğü veya proje koordinasyon becerileri içeriyor."
    },
    "CV has a readable layout layout that covers standard elements." => {
      'tr' => "CV, standart unsurları içeren okunabilir bir düzene sahip."
    },
    # Weaknesses
    "LinkedIn profile connection is missing." => {
      'tr' => "LinkedIn profil bağlantısı eksik."
    },
    "GitHub repository reference is missing." => {
      'tr' => "GitHub depo bağlantısı eksik."
    },
    "Lack of measurable performance metrics and metrics-driven achievements." => {
      'tr' => "Ölçülebilir performans başarıları ve KPI metrikleri eksik."
    },
    "Academic history is missing or lacks standard section labeling." => {
      'tr' => "Eğitim geçmişi eksik veya standart bir başlık altında sunulmamış."
    },
    "Technical skill listing is sparse or contains insufficient technical terminology." => {
      'tr' => "Teknik beceriler bölümü çok seyrek veya yetersiz teknoloji içeriyor."
    },
    # Suggestions
    "Incorporate active LinkedIn and GitHub links in the contact header." => {
      'tr' => "İletişim başlığına aktif LinkedIn ve GitHub linklerini ekleyin."
    },
    "Quantify your achievements with figures: e.g., 'Optimized loading speed by 25%' or 'Managed a server cluster of 50 node instances'." => {
      'tr' => "Başarılarınızı sayısal verilerle ölçülebilir hale getirin: örn. 'Yükleme hızını %25 optimize ettim' veya '50 sunuculuk bir küme yönettim'."
    },
    "Categorize skills explicitly under subheadings (Frontend, Backend, Infrastructure) for recruiter legibility." => {
      'tr' => "Becerileri işe alımcıların kolay okuması için alt başlıklar halinde (Ön yüz, Arka yüz, Altyapı) gruplayın."
    },
    "Integrate tech stacks explicitly into project details to highlight hands-on execution." => {
      'tr' => "Pratik deneyiminizi öne çıkarmak için proje detaylarına kullanılan teknoloji yığınlarını ekleyin."
    },
    "Study and align with critical missing technologies like Docker, CI/CD, and Cloud architectures." => {
      'tr' => "Hedef pozisyonlar için Docker, CI/CD ve Bulut mimarisi gibi kritik eksik teknolojilere odaklanın."
    },
    # Career Descs
    "Focuses on server-side logic, database management, and building high-performance API architectures." => {
      'tr' => "Sunucu tarafı mantığı, veritabanı yönetimi ve yüksek performanslı API mimarileri oluşturmaya odaklanır."
    },
    "Focuses on designing visually stunning user interfaces, user experiences, and single page web applications." => {
      'tr' => "Görsel olarak etkileyici kullanıcı arayüzleri, kullanıcı deneyimi tasarımları ve tek sayfalık web uygulamaları tasarlamaya odaklanır."
    },
    "Bridges the gap between development and operations by maintaining infrastructure, CI/CD pipelines, and cloud scalability." => {
      'tr' => "Altyapıyı, CI/CD süreçlerini ve bulut ölçeklenebilirliğini yöneterek yazılım geliştirme ile operasyonlar arasındaki köprüyü kurar."
    },
    "Analyzes structured/unstructured datasets, builds predictive models, and translates metrics into strategic business insights." => {
      'tr' => "Yapılandırılmış/yapılandırılmamış veri kümelerini analiz eder, tahminleyici modeller oluşturur ve verileri stratejik iş öngörülerine dönüştürür."
    },
    "Handles both client-side and server-side components, building complete end-to-end web applications." => {
      'tr' => "Hem istemci hem de sunucu tarafı bileşenlerini yöneterek uçtan uca eksiksiz web uygulamaları geliştirir."
    }
  }

  def current_locale
    session[:locale] || 'en'
  end

  def t(key)
    DICTIONARY[current_locale][key.to_sym] || key.to_s
  end

  def t_feedback(sentence)
    return "" if sentence.nil?
    mapped = FEEDBACK_MAP[sentence]
    if mapped && mapped[current_locale]
      mapped[current_locale]
    else
      sentence # Fallback to original text
    end
  end

  def score_class(score)
    if score >= 90
      'score-excellent'
    elsif score >= 80
      'score-good'
    elsif score >= 70
      'score-average'
    else
      'score-needs-improvement'
    end
  end

  def format_date(date_str)
    return "" if date_str.nil? || date_str.empty?
    begin
      Time.parse(date_str).strftime('%Y-%m-%d %H:%M')
    rescue => e
      date_str
    end
  end

  def score_badge(score)
    if score >= 90
      "<span class=\"badge badge-success\">#{t(:excellent)}</span>"
    elsif score >= 80
      "<span class=\"badge badge-primary\">#{t(:good)}</span>"
    elsif score >= 70
      "<span class=\"badge badge-warning\">#{t(:average)}</span>"
    else
      "<span class=\"badge badge-danger\">#{t(:critical)}</span>"
    end
  end
end
